### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by thinhbgnex** [teifip/gcic-mqtt-client#3]
I tried NODE_TLS_REJECT_UNAUTHORIZED='0' but not work.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Emitted 'error' event on MqttClient instance at:
    at TLSSocket.handleTLSerrors (/node_modules/mqtt/lib/connect/tls.js:27:18)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

**Comment by thinhbgnex** [comment]
I set `rejectUnauthorized: false` in options and it's work!
